backend:
  name: github
  repo: mcgingras/portv3

media_folder: static/assets

collections:
  - name: blog
    folder: src/blog
    label: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: tags, label: tags }
      - { name: body, label: Body, widget: markdown }
